<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="Camera">
    <xacro:property name="camera_size" value="0.02"/>

    <xacro:macro name="Macro_CameraROS" params="name parent frame image_topic hz *origin fov width height">
        <joint name="${name}_mount_joint" type="fixed">
            <axis xyz="0 1 0"/>
            <xacro:insert_block name="origin"/>
            <parent link="${parent}"/>
            <child link="${frame}"/>
        </joint>

        <!-- Camera -->
        <link name="${frame}">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_size} ${2*camera_size} ${2*camera_size}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_size} ${2*camera_size} ${2*camera_size}"/>
                </geometry>
            </visual>

            <inertial>
                <mass value="1e-5"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
            </inertial>
        </link>

        <gazebo reference="${frame}">
            <sensor type="camera" name="${name}">
                <visualize>true</visualize>
                <update_rate>${hz}</update_rate>
                <camera name="head">
                    <horizontal_fov>${fov}</horizontal_fov>
                    <image>
                        <width>${width}</width>
                        <height>${height}</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>${hz}</updateRate>
                    <cameraName>${name}</cameraName>
                    <imageTopicName>${image_topic}</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>${frame}</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>-0.3299099196112457</distortionK1>
                    <distortionK2>0.125097165288712</distortionK2>
                    <distortionK3>0</distortionK3>
                    <distortionT1>0.001174557712517122</distortionT1>
                    <distortionT2>-0.0006193756409617658</distortionT2>
                </plugin>
            </sensor>
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>
</robot>