joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

HL_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6